// <auto-generated />
using System;
using GenTaskScheduler.SqlServer.Internal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GenTaskScheduler.SqlServer.Migrations
{
    [DbContext(typeof(GenSqlServerContext))]
    [Migration("20250504033328_TriggerRefactor")]
    partial class TriggerRefactor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GenTaskScheduler.Core.Models.Common.CalendarEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CalendarTriggerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Executed")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("ScheduledDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CalendarTriggerId");

                    b.ToTable("CalendarEntries");
                });

            modelBuilder.Entity("GenTaskScheduler.Core.Models.Common.ScheduledTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AutoDelete")
                        .HasColumnType("bit");

                    b.Property<byte[]>("BlobArgs")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DependsOnStatus")
                        .HasColumnType("int");

                    b.Property<Guid?>("DependsOnTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ExecutionStatus")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("NextExecution")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnTaskId");

                    b.ToTable("ScheduledTasks");
                });

            modelBuilder.Entity("GenTaskScheduler.Core.Models.Common.TaskExecutionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("EndedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("ResultBlob")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TriggerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskExecutionsHistory");
                });

            modelBuilder.Entity("GenTaskScheduler.Core.Models.Triggers.BaseTrigger", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<TimeSpan?>("ExecutionInterval")
                        .HasColumnType("time");

                    b.Property<int>("Executions")
                        .HasColumnType("int");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastExecution")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("MaxExecutions")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("NextExecution")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("ShouldAutoDelete")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("TimeOfDay")
                        .HasColumnType("time");

                    b.Property<string>("TriggerDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("Triggers", (string)null);

                    b.HasDiscriminator<string>("TriggerType").HasValue("BaseTrigger");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GenTaskScheduler.Core.Models.Triggers.CalendarTrigger", b =>
                {
                    b.HasBaseType("GenTaskScheduler.Core.Models.Triggers.BaseTrigger");

                    b.HasDiscriminator().HasValue("Calendar");
                });

            modelBuilder.Entity("GenTaskScheduler.Core.Models.Triggers.CronTrigger", b =>
                {
                    b.HasBaseType("GenTaskScheduler.Core.Models.Triggers.BaseTrigger");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasDiscriminator().HasValue("Cron");
                });

            modelBuilder.Entity("GenTaskScheduler.Core.Models.Triggers.DailyTrigger", b =>
                {
                    b.HasBaseType("GenTaskScheduler.Core.Models.Triggers.BaseTrigger");

                    b.HasDiscriminator().HasValue("Daily");
                });

            modelBuilder.Entity("GenTaskScheduler.Core.Models.Triggers.IntervalTrigger", b =>
                {
                    b.HasBaseType("GenTaskScheduler.Core.Models.Triggers.BaseTrigger");

                    b.HasDiscriminator().HasValue("Interval");
                });

            modelBuilder.Entity("GenTaskScheduler.Core.Models.Triggers.MonthlyTrigger", b =>
                {
                    b.HasBaseType("GenTaskScheduler.Core.Models.Triggers.BaseTrigger");

                    b.Property<string>("DaysOfMonth")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MonthsOfYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Monthly");
                });

            modelBuilder.Entity("GenTaskScheduler.Core.Models.Triggers.OnceTrigger", b =>
                {
                    b.HasBaseType("GenTaskScheduler.Core.Models.Triggers.BaseTrigger");

                    b.HasDiscriminator().HasValue("Once");
                });

            modelBuilder.Entity("GenTaskScheduler.Core.Models.Triggers.WeeklyTrigger", b =>
                {
                    b.HasBaseType("GenTaskScheduler.Core.Models.Triggers.BaseTrigger");

                    b.Property<string>("DaysOfWeek")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasDiscriminator().HasValue("Weekly");
                });

            modelBuilder.Entity("GenTaskScheduler.Core.Models.Common.CalendarEntry", b =>
                {
                    b.HasOne("GenTaskScheduler.Core.Models.Triggers.CalendarTrigger", "CalendarTrigger")
                        .WithMany("CalendarEntries")
                        .HasForeignKey("CalendarTriggerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalendarTrigger");
                });

            modelBuilder.Entity("GenTaskScheduler.Core.Models.Common.ScheduledTask", b =>
                {
                    b.HasOne("GenTaskScheduler.Core.Models.Common.ScheduledTask", "DependsOnTask")
                        .WithMany()
                        .HasForeignKey("DependsOnTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DependsOnTask");
                });

            modelBuilder.Entity("GenTaskScheduler.Core.Models.Common.TaskExecutionHistory", b =>
                {
                    b.HasOne("GenTaskScheduler.Core.Models.Common.ScheduledTask", "Task")
                        .WithMany("ExecutionHistory")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("GenTaskScheduler.Core.Models.Triggers.BaseTrigger", b =>
                {
                    b.HasOne("GenTaskScheduler.Core.Models.Common.ScheduledTask", "Task")
                        .WithMany("Triggers")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("GenTaskScheduler.Core.Models.Common.ScheduledTask", b =>
                {
                    b.Navigation("ExecutionHistory");

                    b.Navigation("Triggers");
                });

            modelBuilder.Entity("GenTaskScheduler.Core.Models.Triggers.CalendarTrigger", b =>
                {
                    b.Navigation("CalendarEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
